# This is a basic workflow to help you get started with Actions

name: Frontend-Pull

# Controls when the workflow will run
on:
  pull_request:
    branches: [ develop, main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "⚡ Checkout"
        uses: actions/checkout@v3
      
      - name: "🧪 Setup node"
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          
      - name: "📦 Install Dependencies"
        working-directory: ./client
        run: yarn install --frozen-lockfile
        
      - name: "✅ Run Unit Tests"
        working-directory: ./client
        run: yarn test

