# This is a basic workflow to help you get started with Actions

name: Frontend

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop,main ]
  pull_request:
    branches: [ develop,main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "⚡ Checkout"
        uses: actions/checkout@v3
      
      - name: "🧪 Setup node"
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          
      - name: "📦 Install Dependencies"
        working-directory: ./client
        run: yarn install --frozen-lockfile
              
      - name: "⭐️ Deploy frontend to vercel"  
        uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORGANISATION_ID }}  #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} #Required 
          working-directory: ./client
